### PR TITLE
Transporters/Cargo System

### LINKED ISSUE #86: Transporter system
We should think about a couple things - namely, what can be transported, where does it have to be, how we want to handle locations.

Also we should think about whether we want to do a shuttle system or not.

### PR DESCRIPTION
**Pull request by DakotaHarward**
Here's the Transporters/Cargo System. The Lodash library isn't really required, but I think we should keep it as there's a ton of other cool stuff we can do with it. Closes #86 and #85

### CODE REVIEW

**Review by jextrevor — CHANGES_REQUESTED** [review]
Looks good, but I don't think using the distance function will work. If you look at the latest master, you should be able to see how the objects system does distances now though

**Comment by jextrevor** [comment]
In addition, if you'll look at pull request #153, you'll see how I've switched callbacks from referring to `this` to referring to `Ship.WhateverSystem`, we should do that here too

**Comment by DakotaHarward** [comment]
Ok, I'll fix those things

**Comment by DakotaHarward** [comment]
Alright, check that out

**Review by caydenlund — APPROVED** [review]

**Review by jextrevor — COMMENTED** [review]
I've submitted a pull request for changes that I'd like to see

**Pull request merged**
