### PR TITLE
Issue 26

### PR DESCRIPTION
**Pull request by DakotaHarward**
Closes Issue #26

### CODE REVIEW

**Comment by jextrevor** [comment]
I think the correct notation is "Fixes #26". Let me look at the pull
request in a minute

**Comment by DakotaHarward** [comment]
Closes works too: https://github.com/blog/1386-closing-issues-via-commit-messages (bottom of the post)

**Review by jextrevor — COMMENTED** [review]
Looks great - we'll probably make more changes to it in the future though (like removing the multiple renders to the react-root). Let me test it out really quick and then I'll give my approval.

**Comment by jextrevor** [comment]
Good to know that closes works

**Review by jextrevor — APPROVED** [review]

**Review by caydenlund — APPROVED** [review]

**Pull request merged**
