### PR TITLE
Add template for where to store watches

### LINKED ISSUE #35: Organize place for watches to be stored
Because of the circular dependency issue referenced in #28, we can't have systems watch other system's values immediately on construction - we must instead wait until all systems have been successfully created as keys in the Ship JSON object, then execute some sort of function for each system to start watching others values, as referred to in #30.

Here's an example:
In lifesupport.js (or any other system file)
```
class LifeSupport {
    PowerLifeSupportChanged(){
        //do something
    }
    setupWatches(){
        Ship.Power.watch("LifeSupport",this.PowerLifeSupportChanged)
    }
}
```
In main.js:
```
Ship = {}
Ship.Power = require("systems/power")(io,Ship)
...
Ship.LifeSupport = require("systems/power")(io,Ship)

for(system in Ship){
    system.setupWatches()
}
```

What are your thoughts?

### PR DESCRIPTION
**Pull request by jextrevor**
Fixes #35.

### CODE REVIEW

**Review by caydenlund — APPROVED** [review]

**Review by DakotaHarward — APPROVED** [review]

**Comment by DakotaHarward** [comment]
If I made a mistake on the merge, let me know.

**Comment by jextrevor** [comment]
Okay. I don't think you need to merge master into the branch before you
merge it back into master

**Comment by DakotaHarward** [comment]
Well when you resolve merge conflicts that's how GitHub does it through the web interface. You might not have to do that if you merge locally but I'm not sure.

**Comment by jextrevor** [comment]
Oh, alright. Were there merge conflicts?

**Pull request merged**
