### PR TITLE
Create alert lighting component

### LINKED ISSUE #149: Create alert lighting component
This component will basically create a "light" effect around the edges of a screen that fades in and out, for example if the alert status is red, the edges of the screen will light up red.

### PR DESCRIPTION
**Pull request by jextrevor**
Fixes #149. I've sent you both a video of the component in action: it looks pretty sweet. Let me know if there are any issues or tweaks with how it looks, though.

### CODE REVIEW

**Review by DakotaHarward — APPROVED** [review]
Wow Trevor, this is super cool! I think it would be better though if yellow alert didn't act the same way as red alert. So maybe more time between flashes or maybe it acts the same as green. Just an idea

**Comment by jextrevor** [comment]
True, true... How about it pauses in between flashes for yellow? @DakotaHarward

**Comment by DakotaHarward** [comment]
looks good!

**Review by caydenlund — CHANGES_REQUESTED** [review]
This can work for the main view screen maybe, but for each station it's really invasive.

**Review by caydenlund — APPROVED** [review]

**Pull request merged**
