### PR TITLE
Create position system

### LINKED ISSUE #63: Create position system

### PR DESCRIPTION
**Pull request by jextrevor**
Fixes #63. Also fixes a critical bug in system.js relating to callbacks.

### CODE REVIEW

**Review by DakotaHarward — CHANGES_REQUESTED** [review]
I think we should get rid of the console.logs on lines 23 and 25 in system.js but other than that, it looks great!

**Comment by jextrevor** [comment]
Ohh right, I put those in for testing. Will remove tomorrow

**Comment by DakotaHarward** [comment]
👍

**Comment by jextrevor** [comment]
Ok, I have removed the console.log's @DakotaHarward

**Review by DakotaHarward — APPROVED** [review]

**Pull request merged**
