### PR TITLE
How Media Should Work with MEGA

### PR DESCRIPTION
**Pull request by DakotaHarward**
Here's how I imagine media to work with MEGA. Related to issue #93

### CODE REVIEW

**Review by caydenlund — APPROVED** [review]
Looks good

**Review by jextrevor — CHANGES_REQUESTED** [review]
I don't think we necessarily even need the README.md in the media folder, can we just remove it, along with the exception in the gitignore file?

**Comment by caydenlund** [comment]
Actually, I like the Readme. Can we keep it there?

**Comment by DakotaHarward** [comment]
Well the folders won't be committed unless there's a file in them

**Comment by DakotaHarward** [comment]
I also like the readme

**Review by jextrevor — APPROVED** [review]
Uhhhhhh sure.

**Pull request merged**
