### PR TITLE
Create objects system (should eventually replace position system)

### PR DESCRIPTION
**Pull request by jextrevor**
An objects system has been created that keeps track of all objects, velocities, accelerations, rotations, etc.

Please look over it, *not only* for correctness but also for preference. If you don't like the way I'm handling velocity and acceleration please say so - I know that there's a bunch of places that it can be improved, and I'm sure that this is not the best way to do it.

Thanks

### CODE REVIEW

**Comment by jextrevor** [comment]
For example, we may want to just keep track of velocity and not acceleration to make things easier on ourselves (when doing things with the warp system). It may also be better to keep track of velocity in the polar form and not in the 3 dimensional form.

**Review by caydenlund — APPROVED** [review]
Looks good. I like the way it's set up. One thing: why don't you just pass the data object as the only parameter to the addObject method?

**Comment by jextrevor** [comment]
@shrimpster00 I was thinking the same thing. Let me clean up that right now; I'll make another commit.

**Review by caydenlund — APPROVED** [review]

**Review by caydenlund — CHANGES_REQUESTED** [review]
Remove acceleration. Just use velocity and manipulate it directly.

**Comment by jextrevor** [comment]
Do we want to just store "speed" and apply it along the rotation vector? Or do we want to store velocity in 3 dimensions?

**Review by caydenlund — APPROVED** [review]

**Review by DakotaHarward — APPROVED** [review]

**Pull request merged**
